#!/usr/bin/env python

import findrox; findrox.version(2,0,0)
import rox, os, sys

__builtins__._ = rox.i18n.translation(os.path.join(rox.app_dir, 'Messages'))

import filefind

if len(sys.argv) > 1:
	path = sys.argv[1]
else:
	path = None
	
win = filefind.FindWindow(path)
win.show()
rox.mainloop()
